format = """
$username\
$hostname\
$directory\
$line_break\
$git_branch\
$line_break\
$cmd_duration\
$all\
$shell\
$git_state\
$git_status\
$line_break\
$character"""


[directory]
style = "blue"

[character]
success_symbol = "[>](bold blue)"
error_symbol = "[x](bold red)"
vicmd_symbol = "[<](bold bright-green)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[( *$conflicted$untracked$modified$staged$renamed$deleted)](bold 218) ($ahead_behind$stashed)](bold 218) "
stashed = "≡"
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[shell]
disabled = false
style = "bright-black"

# change all symbols to plain text
[aws]
symbol = "aws "

[c]
symbol = "C "

[cobol]
symbol = "cobol "

[conda]
symbol = "conda "

[crystal]
symbol = "cr "

[cmake]
symbol = "cmake "

[dart]
symbol = "dart "

[deno]
symbol = "deno "

[dotnet]
symbol = ".NET "

[docker_context]
symbol = "docker "

[elixir]
symbol = "exs "

[elm]
symbol = "elm "

[golang]
symbol = "go "

[hg_branch]
symbol = "hg "

[java]
symbol = "java "

[julia]
symbol = "jl "

[kotlin]
symbol = "kt "

[nodejs]
symbol = "nodejs "
format = "[$symbol$version]($style) "

[memory_usage]
symbol = "memory "

[nim]
symbol = "nim "

[nix_shell]
symbol = "nix "

[ocaml]
symbol = "ml "

[package]
symbol = "pkg "

[perl]
symbol = "pl "

[php]
symbol = "php "

[pulumi]
symbol = "pulumi "

[purescript]
symbol = "purs "

[python]
symbol = "py "

[ruby]
symbol = "rb "

[rust]
symbol = "rs "

[scala]
symbol = "scala "

[spack]
symbol = "spack "

[sudo]
symbol = "sudo "

[swift]
symbol = "swift "
